spring:
    datasource:
        username: ${dbUsername}
        url: jdbc:mysql://localhost:3306/FONE_INVEST_CUSTOMER?serverTimezone=Asia/Kathmandu
        password: ${dbPassword}
        devtools:
            add-properties: false
        jpa:
            hibernate:
                naming:
                    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQLDialect


test:
    message: gaurav kumal
    note: remember
