spring:
    datasource:
        password: ${password}
        url: jdbc:mysql://localhost:3306/FONE_INVEST_CUSTOMER?serverTimezone=Asia/Kathmandu
        username: ${username}
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
test:
    message: gaurav kumal
    note: remember
